export const PLAN_LIMITS = {
  free: {
    label: 'Free',
    price: null,
    limits: {
      mentors: 2,
      mentees: 5,
      staff: 2,
      assistant_mentors: 2,
      offerings: 1,
    },
    features: {
      billing: false,
      invoicing: false,
      payroll: false,
      reports: false,
      courses: false,
      arrangements: true,
    },
  },
  starter: {
    label: 'Starter',
    price: 49,
    limits: {
      mentors: 10,
      mentees: 25,
      staff: 5,
      assistant_mentors: 10,
      offerings: 5,
    },
    features: {
      billing: true,
      invoicing: true,
      payroll: false,
      reports: true,
      courses: true,
      arrangements: true,
    },
  },
  pro: {
    label: 'Pro',
    price: 149,
    limits: {
      mentors: 50,
      mentees: 100,
      staff: 20,
      assistant_mentors: 50,
      offerings: Infinity,
    },
    features: {
      billing: true,
      invoicing: true,
      payroll: true,
      reports: true,
      courses: true,
      arrangements: true,
    },
  },
  enterprise: {
    label: 'Enterprise',
    price: null,
    limits: {
      mentors: Infinity,
      mentees: Infinity,
      staff: Infinity,
      assistant_mentors: Infinity,
      offerings: Infinity,
    },
    features: {
      billing: true,
      invoicing: true,
      payroll: true,
      reports: true,
      courses: true,
      arrangements: true,
    },
  },
}
