-- Mentor Tasks: persistent to-do items for mentors.
-- Tasks can be manually created or auto-generated by the journey system
-- when a mentee reaches a decision node.

create table if not exists mentor_tasks (
  id            uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  mentor_id     uuid not null references staff(id) on delete cascade,

  -- Task content
  title         text not null,
  notes         text,
  priority      text not null default 'normal' check (priority in ('normal', 'urgent')),
  status        text not null default 'pending' check (status in ('pending', 'done')),
  due_date      date,

  -- Optional links
  mentee_id          uuid references mentees(id) on delete set null,
  mentee_journey_id  uuid references mentee_journeys(id) on delete set null,
  decision_node_id   text,  -- the node id within the journey content snapshot

  -- Source: 'manual' for mentor-created, 'journey_decision' for auto-created
  source        text not null default 'manual' check (source in ('manual', 'journey_decision')),

  completed_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Indexes for the queries we'll run
create index if not exists idx_mentor_tasks_mentor   on mentor_tasks(mentor_id, status);
create index if not exists idx_mentor_tasks_journey  on mentor_tasks(mentee_journey_id) where mentee_journey_id is not null;

-- RLS
alter table mentor_tasks enable row level security;

create policy "Org members can read own org tasks"
  on mentor_tasks for select
  using (organization_id = (select organization_id from staff where user_id = auth.uid() limit 1));

create policy "Org members can insert own org tasks"
  on mentor_tasks for insert
  with check (organization_id = (select organization_id from staff where user_id = auth.uid() limit 1));

create policy "Org members can update own org tasks"
  on mentor_tasks for update
  using (organization_id = (select organization_id from staff where user_id = auth.uid() limit 1));

create policy "Org members can delete own org tasks"
  on mentor_tasks for delete
  using (organization_id = (select organization_id from staff where user_id = auth.uid() limit 1));
